CREATE TABLE ROLE
(
  ID BIGINT NOT NULL,
  NAME VARCHAR (50) ,
  CONSTRAINT ROLE_PK PRIMARY KEY(ID)
);

CREATE TABLE USERS
(
 ID SERIAL NOT NULL,
 EMAIL VARCHAR (50) NOT NULL UNIQUE,
 PASSWORD VARCHAR (50) NOT NULL,
 ROLE_ID BIGINT NOT NULL,
 FIRST_NAME VARCHAR (50),
 LAST_NAME VARCHAR (50),
 BIRTHDAY DATE,
 CONSTRAINT USERS_PK PRIMARY KEY (ID)
);

ALTER TABLE USERS
  ADD CONSTRAINT FK_USERS_REF_ROLE FOREIGN KEY (ROLE_ID)
  REFERENCES ROLE (ID)
  ON DELETE RESTRICT ON UPDATE RESTRICT;

INSERT INTO ROLE(ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLE(ID, NAME) VALUES (2, 'USER');
INSERT INTO ROLE(ID, NAME) VALUES (3, 'TEACHER');
INSERT INTO ROLE(ID, NAME) VALUES (4, 'STUDENT');

INSERT INTO USERS(EMAIL, PASSWORD, ROLE_ID, FIRST_NAME, LAST_NAME)
VALUES ('admin@inna.home', md5('123123'), 1, 'Admin', 'Admin');

INSERT INTO USERS(EMAIL, PASSWORD, ROLE_ID, FIRST_NAME, LAST_NAME)
VALUES ('i.yaruta@hotmail', md5('111'), 2, 'Inna', 'Yaruta');

INSERT INTO USERS(EMAIL, PASSWORD, ROLE_ID, FIRST_NAME, LAST_NAME)
VALUES ('teacher', md5('123123'), 3, 'Alex', 'Rudenko');

INSERT INTO USERS(EMAIL, PASSWORD, ROLE_ID, FIRST_NAME, LAST_NAME)
VALUES ('student', md5('123123'), 4, 'Alex', 'Rudenko');

CREATE TABLE COURSE
(
ID SERIAL NOT NULL,
FIRST_NAME VARCHAR (50),
DESCRIPTION VARCHAR (250),
START_TIME TIMESTAMP,
END_TIME TIMESTAMP,
PRIMARY KEY (ID)
);